todo_app/users/forms.py
from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import StringField, PasswordField, BooleanField, SubmitField, RadioField
from wtforms.fields.html5 import DateField, EmailField, TelField
from wtforms.validators import DataRequired, Email, EqualTo, InputRequired
from wtforms import ValidationError
from flask_wtf.file import FileField,FileAllowed

from todo_app.models import User

class LoginForm(FlaskForm):

    email = StringField('Email',validators=[DataRequired(),Email()])
    password = PasswordField('Password',validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Log In')

class RegistrationForm(FlaskForm):

    email = EmailField('Email',validators=[DataRequired(),Email()])
    username = StringField('Username',validators=[DataRequired()])
    first_name = StringField('FirstName',validators=[DataRequired()])
    last_name = StringField('LastName',validators=[DataRequired()])
    password = PasswordField('Password',validators=[DataRequired(), EqualTo('pass_confirm', message = "password must match")])
    pass_confirm = PasswordField('Confirm Password',validators=[DataRequired()])
    gender = RadioField('Please choose your mood:', choices=[('M','Male'),('F','Female')])
    terms  = BooleanField("I agree with terms and conditions",validators=[InputRequired()])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')

class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. You must register first.')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password', message = "password must match")])
    submit = SubmitField('Reset Password')

class Change_DpForm(FlaskForm):

    picture = FileField('Pick a Picture',validators=[FileAllowed(['jpg','png'])])
    submit = SubmitField('Update')

class UpdateUserForm(FlaskForm):

    first_name = StringField('FirstName',validators=[DataRequired()])
    last_name = StringField('LastName',validators=[DataRequired()])
    username = StringField('Username',validators=[DataRequired()])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')

todo_app/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from todo_app import db, app, bcrypt
from todo_app.models import User, Todo
from todo_app.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm, Change_DpForm, UpdateUserForm
from todo_app.users.token import get_token, verify_token
from todo_app.users.email import send_reset_email
from todo_app.users.picture import save_picture


users = Blueprint('users',__name__,template_folder='templates/users')


@users.route('/register', methods=['GET','POST'])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():

        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(email=form.email.data,username=form.username.data,first_name=form.first_name.data,last_name=form.last_name.data,gender=form.gender.data,password=hashed_password)

        db.session.add(user)
        db.session.commit()

        flash('Registration Completed', 'info')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)


@users.route('/login', methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user is None:
            flash('This is no user with this email. Please check the email or Register!', 'danger')

        elif bcrypt.check_password_hash(user.password, form.password.data) and user is not None:
            login_user(user, remember=form.remember.data)
            flash('Welcome On-board', 'info')

            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)

        elif bcrypt.check_password_hash(user.password, form.password.data) is None or user is not None:
            flash('Incorrect password', 'danger')

        else:
            flash('Login Unsuccessful. Please check email or password', 'danger')

    return render_template('login.html',form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


#send_reset_email
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):

    user = verify_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password Updated! log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/<username>", methods=['GET','POST'])
def user_todos(username):

    user = User.query.filter_by(username=username).first_or_404()

    form = Change_DpForm()
    if form.validate_on_submit():

        if form.picture.data:
            pic = save_picture(form.picture.data)
            current_user.profile_image = pic
        db.session.commit()
        flash('Profile Image Updated!', 'info')
        return redirect(url_for('users.user_todos', username=current_user.username))

    ROWS_PER_PAGE = 4
    page = request.args.get('page',1,type=int)
    todos = Todo.query.filter_by(author=user).order_by(Todo.date.desc()).paginate(page=page,per_page=ROWS_PER_PAGE)
    return render_template('user_todos.html',todos=todos,user=user,page=page,form=form)


@users.route("/todo/<username>", methods=['GET','POST'])
def all_user_todos(username):

    user = User.query.filter_by(username=username).first_or_404()
    ROWS_PER_PAGE = 5
    page = request.args.get('page',1,type=int)
    todos = Todo.query.filter_by(author=user).order_by(Todo.id.asc()).paginate(page=page,per_page=ROWS_PER_PAGE)

    return render_template('all_user_todo.html',todos=todos,user=user,page=page)

@users.route('/account', methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        current_user.username = form.username.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        db.session.commit()
        flash('User Account Updated!', 'info')
        return redirect(url_for('users.user_todos', username=current_user.username))

    elif request.method == 'GET':
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.username.data = current_user.username

    return render_template('account.html',form=form)

todo_app/users/templates/users/account.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block head %}
    {{ super() }}
    <meta charset="utf-8">
    <title></title>
    <style>
    /* body{background:linear-gradient(to bottom right, rgba(40, 180, 131, 0.3), rgba(0, 0, 131, 0.5)) !important;height: 100vh !important;height:250px;width:600px;margin: auto;} */
    /* body{height:250px;width:600px;margin:auto;background-color:black;} */
    body{
      background-image: url('/static/images/todo7.jpg') !important;
      /* height: 535px; */
      height: 100vh !important;
      width:600px;
      margin: auto;
      background-repeat: none;
      background-attachment: scroll;
      background-position: center center;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }
    p{margin-bottom: 0;}
    </style>
    {% endblock %}
  </head>
  <body>

    {% block content %}

    <div class="jumbotron" style="margin-top:60px;">
      <div align='center'>
        <!-- <h1>Welcome to the page for {{current_user.username}}</h1> -->
        <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
        <p>{{ current_user.email }}</p>
        <p><a href="{{url_for('users.user_todos',username=current_user.username)}}">{{current_user.username}}</a></p>
        <p>{{current_user.first_name}}</p>
        <p>{{current_user.last_name}}</p>
      </div>
    </div>

    <div class="container">
      <form  method="POST" action="" enctype="multipart/form-data">

        {{ form.hidden_tag() }}

        <div class="form-group">
          {{ form.first_name.label(class="form-group") }}

          {% if form.first_name.errors %}
              {{ form.first_name(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                  {% for error in form.first_name.errors %}
                      <span>{{ error }}</span>
                  {% endfor %}
              </div>
          {% else %}
              {{ form.first_name(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.last_name.label(class="form-group") }}

          {% if form.last_name.errors %}
              {{ form.last_name(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                  {% for error in form.last_name.errors %}
                      <span>{{ error }}</span>
                  {% endfor %}
              </div>
          {% else %}
              {{ form.last_name(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.username.label(class="form-group") }}

          {% if form.username.errors %}
              {{ form.username(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                  {% for error in form.username.errors %}
                      <span>{{ error }}</span>
                  {% endfor %}
              </div>
          {% else %}
              {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
            {{ form.submit(class="btn btn-dark") }}
        </div>
      </form>

    </div>

    {% endblock %}


  </body>
</html>

todo_app/users/templates/users/activate.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- CSS only -->
    <style>
    p {padding: 5px;text-align: center;}
    body{height:200px;width:400px;margin:auto;background-color:grey;border:2px solid black;margin-top: 200px}
    .button{background-color:#4caf50;border:none;color:#fff;padding:15px 32px;text-align:center;text-decoration:none;display:inline-block;font-size:16px;margin:4px 2px;cursor:pointer}
    </style>
  </head>
  <body>

    <p>

      To reset your password, visit the following link:
      <br>
      <br>
      <a class="button" href=" {{url_for('users.reset_token', token=token, _external=True)}} ">RESET PASSWORD</a>
      <br>
      <br>
      If you did not make this request then simply ignore this email and no changes will be made.

    </p>

  </body>
</html>

todo_app/users/templates/users/all_user_todo.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block head %}
    {{ super() }}
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/users/all_user_todo.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% endblock %}
  </head>
  <body>

    {% block content %}


      <div class="container center">
        <div class="col-md-8">
          <div class="card-hover-shadow-2x mb-3 card def">
            <div class="card-header-tab card-header">
              <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                <i class="fa fa-tasks"></i>&nbsp;Task Lists
              </div>
            </div>
            <div class="scroll-area-sm deff">
              <perfect-scrollbar class="ps-show-limits">
                <div class="ps ps--active-y">
                  <div class="ps-content">

                    <!-- LOOP FOR TOdo PER USER -->
                    {% for post in todos.items %}
                    <ul class=" list-group list-group-flush">

                      <li class="list-group-item">
                        <div class="todo-indicator bg-warning"></div>
                        <div class="widget-content p-0">
                          <div class="widget-content-wrapper defff">
                            <div class="widget-content-left">
                              <div class="widget-heading">{{post.text}}
                              </div>
                              <div class="widget-subheading"><i>
                                <a href="{{url_for('users.user_todos',username=post.author.username)}}">{{post.author.username}}</a>
                              </i>
                              </div>
                              <div class="widget-subheading">{{ post.date }}</div>
                              <div class="widget-subheading">{{ post.id }}</div>
                            </div>

                          <div class="widget-content-right">
                            <a href="{{url_for('todos.update_todo',todo_iid=post.id)}}">
                              <button class="border-0 btn-transition btn btn-outline-success">
                                <i class="fa fa-edit">
                                </i>
                              </button>
                            </a>

                            <a href="{{url_for('todos.todo',todo_id=post.id)}}">
                              <button type="button" class="border-0 btn-transition btn btn-outline-danger" data-toggle="modal" data-target="#exampleModalLong">
                                <i class="fa fa-trash">
                                </i>
                              </button>
                            </a>

                          </div>
                         </div>
                        </div>
                      </li>

                    </ul>
                    {% endfor %}
                    <!-- END OF LOOP -->

                  </div>
                </div>
              </perfect-scrollbar>
            </div>

            <div class="d-block text-right card-footer">

              <!-- BUTTON -->
              <div class="">
                <a href="{{url_for('core.index')}}"><button class="mr-2 btn btn-link btn-sm">Cancel</button></a>
                <a href="{{url_for('todos.create_todo')}}"><button class="btn btn-primary">Add Task</button></a>
              </div>
              <!-- END OF BUTTON -->

              <!-- START OF PAGINATION -->
              <div class="pagination pag">
                 <a href="{{ url_for('users.all_user_todos', username=user.username, page=todos.prev_num) }}" class="btn btn-outline-primary
                    {% if todos.page == 1 %}disabled{% endif %}">&laquo;
                 </a>

                 {% for page_num in todos.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                     {% if page_num %}

                         {% if todos.page == page_num %}
                         <a class="btn btn-primary" href="{{ url_for('users.all_user_todos', username=user.username, page=page_num) }}">{{ page_num }}</a>
                         {% else %}
                         <a class="btn btn-outline-primary" href="{{ url_for('users.all_user_todos', username=user.username, page=page_num) }}">{{ page_num }}</a>
                         {% endif %}

                     {% else %}
                         ...
                     {% endif %}
                 {% endfor %}

                 <a href="{{ url_for('users.all_user_todos', username=user.username, page=todos.next_num) }}" class="btn btn-outline-primary
                    {% if todos.page == todos.pages %}disabled{% endif %}">&raquo;
                 </a>
             </div>

             <p class="text-center mt-8 pg">
                Showing page {{ todos.page }} of {{ todos.pages }}
             </p>

             <!-- END OF PAGINATION -->
            </div>

          </div>
        </div>
        </div>




    {% endblock %}


    {% block scripts %}
    {{ super() }}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" charset="utf-8"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" charset="utf-8"></script>
    {% endblock %}

  </body>
</html>

todo_app/users/templates/users/login.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block head %}
    {{ super() }}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/users/login.css') }}"> -->
    <title></title>
    {% endblock %}
  </head>
  <body>
    {% block content %}

    <section class="vh-100" style="height: 100vh;background: linear-gradient(to bottom right, rgba(40, 180, 131, 0.3), rgba(0, 0, 131, 0.5));">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-xl-10" style="margin-top:10px;">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-6 col-lg-5 d-none d-md-block">
                  <!-- <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp" -->
                  <img src="{{url_for('static',filename='images/todo5.jpg')}}" height="100px"
                    alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;height:550px;width:600px;" />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">

                    <form method="POST">

                      {{ form.hidden_tag() }}

                      <div class="d-flex align-items-center mb-3 pb-1">
                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                        <span class="h1 fw-bold mb-0">Logo</span>
                      </div>

                      <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>

                      <div class="form-outline mb-4">
                        {{ form.email.label(class="form-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg",placeholder="email") }}
                        {% endif %}
                      </div>

                      <div class="form-outline mb-4">
                        {{ form.password.label(class="form-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg",placeholder="password") }}
                        {% endif %}
                      </div>

                      <div class="pt-1 mb-4">
                        {{ form.submit(class="btn btn-outline-dark btn-lg btn-block") }}
                      </div>

                      <a class="ml" href="{{ url_for('users.reset_request') }}">Forgot password?</a>
                      <p class="mb-5 pb-lg-2">Don't have an account? <a class="ml-1"href="{{ url_for('users.register') }}">Register here</a></p>
                      <a href="#!" class="small text-muted">Terms of use.</a>
                      <a href="#!" class="small text-muted">Privacy policy</a>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

<!-- style="color: #393f81;" -->

todo_app/users/templates/users/register.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block head %}
    {{ super()}}

    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/users/register.css') }}">
    {% endblock %}

  </head>
  <body>

    {% block content %}



    <div class="form_wrapper">
  <div class="form_container">
    <div class="title_container">
      <h2>Responsive Registration Form</h2>
    </div>
    <div class="row clearfix">
      <div class="">
        <form method="POST">
          {{ form.hidden_tag() }}
          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-envelope"></i></span>
              <!-- {{ form.email.label() }} -->
              {% if form.email.errors %}
                  {{ form.email(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.email(placeholder="Email")}}
              {% endif %}
          </div>

          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-user"></i></span>
              <!-- {{ form.username.label(class="form-control-label") }} -->

              {% if form.username.errors %}
                  {{ form.username(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.username.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.username(placeholder="username") }}
              {% endif %}
          </div>

          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-lock"></i></span>
              <!-- {{ form.password.label() }} -->
              {% if form.password.errors %}
                  {{ form.password(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.password.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.password(placeholder="Password") }}
              {% endif %}
          </div>

          <div class="input_field"> <span><i aria-hidden="true" class="fa fa-lock"></i></span>
              <!-- {{ form.pass_confirm.label(class="form-control-label") }} -->
              {% if form.pass_confirm.errors %}
                  {{ form.pass_confirm(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in pass_confirm.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.pass_confirm(placeholder="Re-type Password") }}
              {% endif %}
          </div>


          <div class="row clearfix">
            <div class="col_half">
              <div class="input_field"> <span><i aria-hidden="true" class="fa fa-user"></i></span>
                  <!-- {{ form.first_name.label(class="form-control-label") }} -->
                  {% if form.first_name.errors %}
                      {{ form.first_name(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.first_name.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.first_name(placeholder="First_Name") }}
                  {% endif %}
              </div>
            </div>
            <div class="col_half">
              <div class="input_field"> <span><i aria-hidden="true" class="fa fa-user"></i></span>
                  <!-- {{ form.last_name.label(class="form-control-label") }} -->
                  {% if form.last_name.errors %}
                      {{ form.last_name(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.last_name.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.last_name(placeholder="Last_Name") }}
                  {% endif %}
              </div>
            </div>
          </div>

            	<div class="input_field radio_option">
                {% if form.gender.errors %}
                    {{ form.gender() }}
                    <div class="invalid-feedback">
                        {% for error in form.gender.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.gender() }}
                {% endif %}
              </div>

            <div class="input_field checkbox_option">
              {% if form.terms.errors %}
                  {{ form.terms() }}
                  <div class="invalid-feedback">
                      {% for error in form.terms.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.terms() }}
              {% endif %}
              {{ form.terms.label() }}
            </div>

          <div class="">
              {{ form.submit(class="button") }}
          </div>

        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-1" href="{{ url_for('users.login') }}">Sign In</a>
            </small>
        </div>
      </div>
    </div>
  </div>
</div>

    {% endblock %}




    {% block scripts %}
    {{ super() }}
    <script src='https://use.fontawesome.com/4ecc3dbb0b.js'></script>
    {% endblock %}


  </body>
</html>

todo_app/users/templates/users/reset_request.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block head %}
    {{ super() }}
    <meta charset="utf-8">
    <title></title>
    <style>
    body{height:250px;width:400px;margin:auto;background-color: black !important;border:2px solid white;margin-top: 200px}
    .mee{color: white;}
    </style>
    {% endblock %}
  </head>
  <body>

    {% block content %}

    <div class="container">

      <div class="content-section">
          <form method="POST" action="">
              {{ form.hidden_tag() }}
              <fieldset class="form-group">
                  <legend class="border-bottom mb-4 mee">Reset Password</legend>
                  <div class="form-group">
                      {{ form.email.label(class="form-control-label mee") }}
                      {% if form.email.errors %}
                          {{ form.email(class="form-control form-control-lg is-invalid") }}
                          <div class="invalid-feedback">
                              {% for error in form.email.errors %}
                                  <span>{{ error }}</span>
                              {% endfor %}
                          </div>
                      {% else %}
                          {{ form.email(class="form-control form-control-lg",placeholder="Enter Email Address:") }}
                      {% endif %}
                  </div>
              </fieldset>
              <div class="form-group">
                  {{ form.submit(class="btn btn-outline-dark") }}
              </div>
          </form>
      </div>

    </div>

    {% endblock %}


  </body>
</html>