todo_app/core/views.py
from flask import render_template,request,Blueprint


core = Blueprint('core',__name__,template_folder='templates/core')

@core.route('/')
def index():
    return render_template('main.html')

todo_app/todo/views.py
import datetime
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from todo_app import db
from todo_app.models import User, Todo
from todo_app.todo.forms import TodoForm

todos = Blueprint('todos',__name__,template_folder='templates/todo')


@todos.route('/create', methods=['GET','POST'])
@login_required
def create_todo():

    form = TodoForm()

    if form.validate_on_submit():

        todo = Todo(text=form.text.data,date=form.date.data,user_id=current_user.username)
        db.session.add(todo)
        db.session.commit()
        flash('Todo Created!', 'info')
        return redirect(url_for('users.all_user_todos', username=current_user.username))

    return render_template('create_todo.html',form=form)

@todos.route('/todo/<int:todo_id>')
@login_required
def todo(todo_id):
    todos = Todo.query.get_or_404(todo_id)
    return render_template('todo.html',todos=todos)

@todos.route("/<int:todo_iid>/update_todo", methods=['GET', 'POST'])
@login_required
def update_todo(todo_iid):
    todo = Todo.query.get_or_404(todo_iid)
    if todo.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = TodoForm()
    if form.validate_on_submit():
        todo.text = form.text.data
        todo.date = form.date.data
        db.session.commit()
        flash('Todo Updated', 'info')
        return redirect(url_for('users.all_user_todos', username=current_user.username))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.text.data = todo.text
        form.date.data = todo.date

    return render_template('create_todo.html',form=form,todo=todo)

@todos.route("/<int:todo_id>/delete", methods=['POST'])
@login_required
def delete_todo(todo_id):
    todo = Todo.query.get_or_404(todo_id)
    if todo.author != current_user:
        abort(403)
    db.session.delete(todo)
    db.session.commit()
    flash('Post has been deleted', 'danger')
    return redirect(url_for('users.all_user_todos',username=current_user.username))

todo_app/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from todo_app import db, app, bcrypt
from todo_app.models import User, Todo
from todo_app.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm, Change_DpForm, UpdateUserForm
from todo_app.users.token import get_token, verify_token
from todo_app.users.email import send_reset_email
from todo_app.users.picture import save_picture


users = Blueprint('users',__name__,template_folder='templates/users')


@users.route('/register', methods=['GET','POST'])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():

        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(email=form.email.data,username=form.username.data,first_name=form.first_name.data,last_name=form.last_name.data,gender=form.gender.data,password=hashed_password)

        db.session.add(user)
        db.session.commit()

        flash('Registration Completed', 'info')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)


@users.route('/login', methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user is None:
            flash('This is no user with this email. Please check the email or Register!', 'danger')

        elif bcrypt.check_password_hash(user.password, form.password.data) and user is not None:
            login_user(user, remember=form.remember.data)
            flash('Welcome On-board', 'info')

            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)

        elif bcrypt.check_password_hash(user.password, form.password.data) is None or user is not None:
            flash('Incorrect password', 'danger')

        else:
            flash('Login Unsuccessful. Please check email or password', 'danger')

    return render_template('login.html',form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


#send_reset_email
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):

    user = verify_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password Updated! log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/<username>", methods=['GET','POST'])
def user_todos(username):

    user = User.query.filter_by(username=username).first_or_404()

    form = Change_DpForm()
    if form.validate_on_submit():

        if form.picture.data:
            pic = save_picture(form.picture.data)
            current_user.profile_image = pic
        db.session.commit()
        flash('Profile Image Updated!', 'info')
        return redirect(url_for('users.user_todos', username=current_user.username))

    ROWS_PER_PAGE = 4
    page = request.args.get('page',1,type=int)
    todos = Todo.query.filter_by(author=user).order_by(Todo.date.desc()).paginate(page=page,per_page=ROWS_PER_PAGE)
    return render_template('user_todos.html',todos=todos,user=user,page=page,form=form)


@users.route("/todo/<username>", methods=['GET','POST'])
def all_user_todos(username):

    user = User.query.filter_by(username=username).first_or_404()
    ROWS_PER_PAGE = 5
    page = request.args.get('page',1,type=int)
    todos = Todo.query.filter_by(author=user).order_by(Todo.id.asc()).paginate(page=page,per_page=ROWS_PER_PAGE)

    return render_template('all_user_todo.html',todos=todos,user=user,page=page)

@users.route('/account', methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        current_user.username = form.username.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        db.session.commit()
        flash('User Account Updated!', 'info')
        return redirect(url_for('users.user_todos', username=current_user.username))

    elif request.method == 'GET':
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.username.data = current_user.username

    return render_template('account.html',form=form)

todo_app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block head %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style media="screen">
     .aa{font-weight: 700;font-family: sans-serif;color: green;}
     /* .meg{margin-left: 20px} */
    </style>
    {% endblock %}
    <title></title>
  </head>
  <body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('core.index') }}">Shabzy Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('core.index') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">

              {% if current_user.is_authenticated %}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Todo
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{{ url_for('todos.create_todo') }}">Create To-do</a>
                  <a class="dropdown-item" href="{{ url_for('users.all_user_todos', username=current_user.username) }}">Todos</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{{ url_for('users.user_todos', username=current_user.username) }}">Profile</a>
                  <a class="dropdown-item" href="{{ url_for('users.account') }}">Profile setting</a>
                </div>
              </li>

              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>

              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}

            </div>

            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            
          </div>
        </div>
      </nav>
    </header>

    {% block content %}
    {% endblock %}


    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock %}
  </body>
</html>