todo_app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.fields.html5 import DateField

from wtforms.validators import DataRequired


class TodoForm(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later
    text = TextAreaField('Todo', validators=[DataRequired(message = "Fill in Task")])
    date = DateField('Your Date:')
    submit = SubmitField('Post')

# , format='%m/%d/%y'
# {{url_for('todos.update',todo_iid=todos.id)}}

todo_app/todo/views.py
import datetime
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from todo_app import db
from todo_app.models import User, Todo
from todo_app.todo.forms import TodoForm

todos = Blueprint('todos',__name__,template_folder='templates/todo')


@todos.route('/create', methods=['GET','POST'])
@login_required
def create_todo():

    form = TodoForm()

    if form.validate_on_submit():

        todo = Todo(text=form.text.data,date=form.date.data,user_id=current_user.username)
        db.session.add(todo)
        db.session.commit()
        flash('Todo Created!', 'info')
        return redirect(url_for('users.all_user_todos', username=current_user.username))

    return render_template('create_todo.html',form=form)

@todos.route('/todo/<int:todo_id>')
@login_required
def todo(todo_id):
    todos = Todo.query.get_or_404(todo_id)
    return render_template('todo.html',todos=todos)

@todos.route("/<int:todo_iid>/update_todo", methods=['GET', 'POST'])
@login_required
def update_todo(todo_iid):
    todo = Todo.query.get_or_404(todo_iid)
    if todo.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = TodoForm()
    if form.validate_on_submit():
        todo.text = form.text.data
        todo.date = form.date.data
        db.session.commit()
        flash('Todo Updated', 'info')
        return redirect(url_for('users.all_user_todos', username=current_user.username))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.text.data = todo.text
        form.date.data = todo.date

    return render_template('create_todo.html',form=form,todo=todo)

@todos.route("/<int:todo_id>/delete", methods=['POST'])
@login_required
def delete_todo(todo_id):
    todo = Todo.query.get_or_404(todo_id)
    if todo.author != current_user:
        abort(403)
    db.session.delete(todo)
    db.session.commit()
    flash('Post has been deleted', 'danger')
    return redirect(url_for('users.all_user_todos',username=current_user.username))

todo_app/todo/templates/todo/create_todo.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block head%}
    {{ super() }}
    <meta charset="utf-8">
    <title></title>
    <style>
    /* body{background:linear-gradient(to bottom right, rgba(40, 180, 131, 0.3), rgba(0, 0, 131, 0.5)) !important;height: 100vh !important;} */
    body{
      background-image: url('/static/images/todo4.jpg') !important;
      /* height: 535px; */
      height: 75vh !important;
      background-repeat: none;
      background-attachment: scroll;
      background-position: center center;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }
    .con{width: 600px;margin: auto;margin-top:120px;}
    .lab{font-size: 25px;}
    </style>
    {% endblock%}
  </head>
  <body>

    {% block content %}

    <div class="container con">
      <form method="POST" action="">

        {{ form.hidden_tag() }}

         <div class="form-group">
         {{ form.text.label(class="form-control-label lab") }}
         {{ form.text(class="form-control form-control-lg",placeholder="fill in task") }}
         </div>
         <div class="form-group">
         {{ form.date.label(class="form-control-label lab") }}
         {{ form.date(class="form-control form-control-lg") }}
         </div>
         <div class="form-group">
         {{ form.submit(class="btn btn-dark") }}
         </div>

      </form>
    </div>

    {% endblock %}

  </body>
</html>

todo_app/todo/templates/todo/todo.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
    body{height: 489px;width:400px;margin:auto;background: linear-gradient(to bottom right, rgba(40, 180, 131, 0.3), rgba(0, 0, 131, 0.5));}
    .me{border:2px solid black;padding-left: 10px;justify-content: center;margin-top: 200px;}
    .mee{display: flex;justify-content: center;margin-top: 50px;}
    </style>

  </head>
  <body>

    <div class="me">

      <h1>{{ todos.text }}</h1>
      <h2>Written by: {{ todos.author.username }}</h2>
      <h3>Published: {{ todos.date }}</h3>

    {% if todos.author == current_user %}
      <div class="mee">

        <a href="{{ url_for('users.all_user_todos', username=current_user.username) }}">
          <button class="btn btn-primary">Go Back</button>
        </a>
        <div>
          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
        </div>

      </div>
    {% endif %}

    </div>

          <!-- Modal for Pop Up-->
          {# https://getbootstrap.com/docs/4.1/components/modal/ #}
          {# Notice how the link with the id to the button above! #}
          <div class="modal" tabindex="-1" role="dialog" id="del_modal">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Delete Task Pop up Modal</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>Are you sure you want to delete this task?</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                  <form action="{{ url_for('todos.delete_todo', todo_id=todos.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Yes">
                  </form>

                </div>
              </div>
            </div>
          </div>

          <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>